---
# Manage some Galaxy configuration files

- name: Configuration files from templates setup
  block:

    - name: Create Galaxy auth_conf.xml file
      template:
        src: "auth_conf.xml.j2"
        dest: "{{ galaxy_config_file }}"
        backup: "{{ galaxy_backup_configfiles }}"
      notify:
        - "{{ galaxy_restart_handler_name | default('default restart galaxy handler') }}"

  remote_user: "{{ galaxy_remote_users.errdocs | default(omit) }}"
  become: "{{ true if galaxy_become_users.errdocs is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.errdocs | default(ansible_user_id) }}"
